In [124]:
import os
import numpy as np
import pandas as pd
from PIL import Image
import zipfile
from numpy.linalg import eig
import matplotlib.pyplot as plt
os.environ['KMP_DUPLICATE_LIB_OK']='True'

In [146]:
imageSize = (1600, 1600)

In [147]:
def getImagesVector(folderName,ext,no_of_imgs):
    imgs=[]
    for i in range(1,no_of_imgs):
        img = Image.open('E:/MS-1/Stats & Math/Assignment/'+folderName+'/'+str(i)+'.'+ext).convert('L')
        img = img.resize(imageSize)
        arr = np.array(img)
        #to vector
        flat_arr = arr.ravel()
        imgs.append(flat_arr)
    return  imgs  

In [148]:
rizz=np.array(getImagesVector('Rizwan','jpg',10))
rizz[0:1]

array([[72, 74, 75, ..., 41, 37, 36]], dtype=uint8)

In [149]:
salu=getImagesVector('Salman','jpg',10)

In [150]:
haider=getImagesVector('Haider','jpg',10)

In [151]:
sajid=getImagesVector('Sajid','jpeg',10)

In [152]:
data=np.append(rizz,salu,axis=0)
data[0:1]

array([[72, 74, 75, ..., 41, 37, 36]], dtype=uint8)

In [153]:
data=np.append(data,haider,axis=0)

In [154]:
data=np.append(data,sajid,axis=0)

In [155]:
data.shape

(36, 2560000)

In [156]:
face_vector = np.array(imgs)
data_copy=face_vector.T

In [157]:
data_copy=data.T
data_copy.shape

(2560000, 36)

In [158]:
mean=np.array([np.mean(data_copy,axis=1)])
mean=mean.T
mean.shape

(2560000, 1)

In [159]:
I=data_copy-mean
I.shape

(2560000, 36)

In [160]:
It=I.T
It.shape

(36, 2560000)

In [161]:
covamatrix=np.dot(It,I)
covamatrix.shape

(36, 36)

In [162]:
eigval,eigvec=eig(covamatrix)
eigvec.shape

(36, 36)

In [165]:
res=np.zeros([36,1])
res.shape

(36, 1)

In [ ]:
for i in range(len(eigval)):
    res[i]=(eigval[i]/np.sum(eigval))*100
    print('Eigen Value',i,'=',res[i])

In [167]:
k = 36
k_eigen_vectors = eigvec[:,0:k]

In [ ]:
eigface=I.dot(k_eigen_vectors)
for i in range(0,35):
    img=(eigface.T[i].reshape(imageSize))
    plt.imshow(img, cmap="gray")
    plt.show()

In [169]:
eigface.shape

(2560000, 36)

In [170]:
I.shape

(2560000, 36)

In [171]:
pc=It.dot(eigface)
pc.shape 

(36, 36)

In [172]:
reconstructed=np.dot(np.linalg.pinv(eigface).T,pc.T)
reconstructed.shape

(2560000, 36)

In [173]:
final=reconstructed.T+mean.T
print(final[0:1])
print(data[0:1])

[[72. 74. 75. ... 41. 37. 36.]]
[[72 74 75 ... 41 37 36]]


In [174]:
final[0].shape

(2560000,)

In [ ]:
for i in range(0,35):
    img=(final[i].reshape(imageSize))
    plt.imshow(img, cmap="gray")
    plt.show()
   

In [176]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [177]:
X=pc
Y=['Rizwan','Rizwan','Rizwan','Rizwan','Rizwan','Rizwan','Rizwan','Rizwan','Rizwan',
   'Salman','Salman','Salman','Salman','Salman','Salman','Salman','Salman','Salman',
   'Haider','Haider','Haider','Haider','Haider','Haider','Haider','Haider','Haider',
   'Sajid','Sajid','Sajid','Sajid','Sajid','Sajid','Sajid','Sajid','Sajid',
    ]
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [178]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=4)

In [179]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=4)

In [180]:
knn.score(X_test,y_test)

1.0

In [ ]:
for i in range(0,35):
    ms=data[i]-mean.T
    ms=ms.dot(v.T)
    print(i,knn.predict(ms))

In [182]:
k = 30
k_eigen_vectors = eigvec[:,0:k]
pc=It.dot(eigface)
reconstructed=np.dot(np.linalg.pinv(eigface).T,pc.T)
final=reconstructed.T+mean.T
print(final[0:1])
print(data[0:1])

[[72. 74. 75. ... 41. 37. 36.]]
[[72 74 75 ... 41 37 36]]


In [183]:
X=pc
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
knn=KNeighborsClassifier(n_neighbors=4)
knn.fit(X_train,y_train)
knn.score(X_test,y_test)

1.0

In [184]:
k = 20
k_eigen_vectors = eigvec[:,0:k]
pc=It.dot(eigface)
reconstructed=np.dot(np.linalg.pinv(eigface).T,pc.T)
final=reconstructed.T+mean.T
print(final[0:1])
print(data[0:1])
X=pc
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
knn=KNeighborsClassifier(n_neighbors=4)
knn.fit(X_train,y_train)
knn.score(X_test,y_test)

[[72. 74. 75. ... 41. 37. 36.]]
[[72 74 75 ... 41 37 36]]


1.0

In [185]:
k = 10
k_eigen_vectors = eigvec[:,0:k]
pc=It.dot(eigface)
reconstructed=np.dot(np.linalg.pinv(eigface).T,pc.T)
final=reconstructed.T+mean.T
print(final[0:1])
print(data[0:1])
X=pc
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
knn=KNeighborsClassifier(n_neighbors=4)
knn.fit(X_train,y_train)
knn.score(X_test,y_test)

[[72. 74. 75. ... 41. 37. 36.]]
[[72 74 75 ... 41 37 36]]


1.0

In [186]:
k = 5
k_eigen_vectors = eigvec[:,0:k]
pc=It.dot(eigface)
reconstructed=np.dot(np.linalg.pinv(eigface).T,pc.T)
final=reconstructed.T+mean.T
print(final[0:1])
print(data[0:1])
X=pc
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
knn=KNeighborsClassifier(n_neighbors=4)
knn.fit(X_train,y_train)
knn.score(X_test,y_test)

[[72. 74. 75. ... 41. 37. 36.]]
[[72 74 75 ... 41 37 36]]


1.0

In [ ]:
for i in range(0,35):
    img=(final[i].reshape(imageSize))
    plt.imshow(img, cmap="gray")
    plt.show()

In [188]:
k = 1
k_eigen_vectors = eigvec[:,0:k]
pc=It.dot(eigface)
reconstructed=np.dot(np.linalg.pinv(eigface).T,pc.T)
final=reconstructed.T+mean.T
print(final[0:1])
print(data[0:1])
X=pc
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
knn=KNeighborsClassifier(n_neighbors=4)
knn.fit(X_train,y_train)
knn.score(X_test,y_test)

[[72. 74. 75. ... 41. 37. 36.]]
[[72 74 75 ... 41 37 36]]


1.0

In [ ]:
for i in range(0,35):
    img=(final[i].reshape(imageSize))
    plt.imshow(img, cmap="gray")
    plt.show()

# Report
- I just make a minor change in reconstruction method and as can see my with only one eigen vector my results are 100% <br>
- The change is very simple which we have studied in our high school math <br>

- **PCA = Meansubtracted_Data * Eigen_vector <br>**
- **Recon = PCA * Inverse(Eigen_Vector)**